/*
  Fix USP_GET_USERS_FOR_DAY_END_NUDGE.

  Previous version called USP_GET_USERS_DAY_END, which only returns users at the
  exact day-end minute — disjoint from the "30 minutes before close" nudge window.
  This version reads open USERDAY rows joined to RULE_MANAGEMENT.RULE_SET boundaries.
*/
CREATE OR ALTER PROCEDURE [dbo].[USP_GET_USERS_FOR_DAY_END_NUDGE]
(
    @UTCTIME DATETIME2,
    @NUDGEMINUTES INT = 30
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        UD.USERID,
        UD.DAYID,
        UD.DAYNUMBER,
        UD.DAYDATE,
        RS.CURRENTDAYENDUTC,
        UD.TOTALRULES,
        UD.COMPLETEDRULES,
        (UD.TOTALRULES - UD.COMPLETEDRULES) AS REMAININGRULES,
        RS.TIMEZONE
    FROM dbo.USERDAY UD
    INNER JOIN [RULE_MANAGEMENT].[dbo].[RULE_SET] RS
        ON RS.USERID = UD.USERID
       AND RS.ACTIVE = 1
    WHERE UD.STATUS = N'OPEN'
      AND UD.RESULT IS NULL
      AND UD.TOTALRULES > UD.COMPLETEDRULES
      AND RS.CURRENTDAYENDUTC IS NOT NULL
      AND RS.CURRENTDAYID = UD.DAYID
      AND DATEADD(MINUTE, -@NUDGEMINUTES, RS.CURRENTDAYENDUTC) <= @UTCTIME
      AND @UTCTIME < RS.CURRENTDAYENDUTC
    ORDER BY RS.CURRENTDAYENDUTC, UD.USERID;
END
GO
